int roll_die(int);
int check_damage(int, int, int);
int reduce_health(int health, int damage);
int get_damage_roll(bool, int, std::string, int);
int mod_damage_roll(int, std::string);
int get_evasion(std::string profession, int level);
int get_attack(std::string profession, int level);
int get_maximum_health(std::string profession, int level);
int get_defense(std::string profession, int level);
int get_power(std::string profession, int level);
int refresh_player_counter(std::string, int);
int refresh_crit_counter(std::string, std::string, int, int);
int check_apply_conditions(std::string, bool, int);
int check_apply_blindness(std::string, bool, int);
bool check_hit(int, int, std::string, std::string);
bool check_win(int health);
bool flip_coin(void);
std::string get_player_name(void);
std::string get_player_profession(void);
std::string get_story(int);
std::string make_space(int number_of_lines);
std::string get_move_selection(std::string, std::string, std::string);
std::string get_parameter(std::string, std::string);
void read_info_bar(std::string name, int level, int health, int conditions);
void read_story_lines(int starting_line, int ending_line);
void read_story_scene(int chapter, int stage, int scene);
void read_combat_move(std::string, std::string);
void read_attack_success(std::string attacker_name, std::string defender_name, std::string, int damage);
void read_attack_success(std::string, std::string, std::string, std::string);
void read_attack_failure(std::string, std::string, std::string);
void read_combat_miss(std::string attacker_name, std::string defender_name);
void read_combat_conditions(std::string name, int damage);
void read_combat_draw(std::string, std::string);
void read_combat_win(std::string, std::string);
void read_combat_loss(std::string, std::string);
void read_combat_hidden(std::string);
void read_game_over(std::string, std::string);